name: cli_progress
description: Command-line progress bar for Dart.
version: 0.0.1
author: Roman Vanesyan <roman@vanesyan.me>
homepage: https://github.com/vanesyan/progress.dart
environment:
  sdk: '>=1.24.0 <2.0.0'
